import { describe, it, expect } from 'vitest';
import {
  rankineOvoid,
  solveBodyOfRevolution,
  type BodyStation,
} from '../src/physics/panel/bodyOfRevolution';

/**
 * The fuselage solver, against the one axisymmetric body whose answer is known exactly
 * and which a line-source method has no excuse for getting wrong.
 *
 * A Rankine ovoid is generated by a point source and an equal sink in a uniform stream,
 * so its surface, and the pressure on it, are closed-form. A sphere would be the more
 * familiar check and the wrong one: it needs a point doublet, and no distribution along
 * an axis represents it well. Checking against a shape the method cannot represent would
 * only measure that mismatch.
 */

const comparison = (strength: number) => {
  const exact = rankineOvoid(strength, 1, 80);
  const solved = solveBodyOfRevolution(exact.stations);
  const maxRadius = Math.max(...exact.stations.map((s) => s.radius));

  let sum = 0;
  let count = 0;
  for (let i = 0; i < exact.cp.length; i++) {
    if (exact.stations[i].radius < 0.06 * maxRadius) continue;
    sum += Math.abs(solved.cp[i] - exact.cp[i]);
    count++;
  }
  const length = exact.stations[exact.stations.length - 1].x - exact.stations[0].x;
  return {
    meanError: sum / count,
    exactPeak: Math.min(...exact.cp),
    solvedPeak: Math.min(...solved.cp),
    fineness: length / (2 * maxRadius),
    solved,
  };
};

describe('against the exact Rankine ovoid', () => {
  it('recovers the pressure distribution', () => {
    for (const strength of [2, 1, 0.4]) {
      const { meanError } = comparison(strength);
      expect(meanError).toBeLessThan(0.02);
    }
  });

  it('puts the suction peak within a few thousandths of the exact one', () => {
    for (const strength of [2, 1, 0.4]) {
      const { exactPeak, solvedPeak } = comparison(strength);
      expect(solvedPeak).toBeCloseTo(exactPeak, 2);
    }
  });

  it('weakens the suction as the body slims down, as it must', () => {
    const blunt = comparison(2);
    const middling = comparison(1);
    const slim = comparison(0.4);
    expect(blunt.fineness).toBeLessThan(middling.fineness);
    expect(middling.fineness).toBeLessThan(slim.fineness);
    expect(blunt.exactPeak).toBeLessThan(middling.exactPeak);
    expect(blunt.solvedPeak).toBeLessThan(middling.solvedPeak);
    expect(middling.solvedPeak).toBeLessThan(slim.solvedPeak);
  });

  /**
   * The method has a limit, and it is worth stating rather than discovering. A very
   * slender ovoid is a needle, and a line of sources on the axis of a needle sits
   * essentially on its surface. Mean error there is about 0.08 rather than 0.007. It
   * does not matter for a fuselage, whose fineness is similar but whose nose is blunt,
   * and the test exists so that nobody takes the method somewhere it does not go.
   */
  it('degrades on a needle, which a fuselage is not', () => {
    expect(comparison(0.03).meanError).toBeGreaterThan(0.02);
  });
});

/** A fuselage-shaped body: blunt nose, long parallel barrel, tapered tail. */
function fuselage(length: number, radius: number, samples = 70): BodyStation[] {
  const stations: BodyStation[] = [];
  for (let i = 0; i < samples; i++) {
    const t = 0.5 * (1 - Math.cos((Math.PI * i) / (samples - 1)));
    let r: number;
    if (t < 0.12) r = radius * Math.sqrt(1 - ((0.12 - t) / 0.12) ** 2);
    else if (t > 0.72) r = radius * (1 - ((t - 0.72) / 0.28) ** 2 * 0.95);
    else r = radius;
    stations.push({ x: t * length, radius: Math.max(0, r) });
  }
  return stations;
}

describe('on a fuselage', () => {
  const solved = solveBodyOfRevolution(fuselage(38, 1.88));

  it('stops the flow at the nose', () => {
    expect(solved.cp[0]).toBeCloseTo(1, 6);
  });

  it('never claims a pressure above stagnation', () => {
    // Incompressible flow has no way to recover more than the whole dynamic pressure.
    for (const cp of solved.cp) expect(cp).toBeLessThanOrEqual(1 + 1e-9);
  });

  it('accelerates the flow over the shoulder, where the body stops growing', () => {
    // Just aft of the nose fairing, where the curvature turns over.
    const shoulder = solved.cp.filter((_, i) => solved.x[i] > 3 && solved.x[i] < 8);
    expect(Math.min(...shoulder)).toBeLessThan(-0.02);
  });

  it('settles down along the parallel barrel', () => {
    const barrel = solved.cp.filter((_, i) => solved.x[i] > 14 && solved.x[i] < 24);
    for (const cp of barrel) expect(Math.abs(cp)).toBeLessThan(0.1);
  });
});

describe('degenerate input', () => {
  it('returns a flat answer rather than throwing', () => {
    expect(solveBodyOfRevolution([]).cp).toHaveLength(0);
    expect(solveBodyOfRevolution([{ x: 0, radius: 1 }]).cp).toHaveLength(1);
    const flat = solveBodyOfRevolution([
      { x: 0, radius: 0 },
      { x: 1, radius: 0 },
      { x: 2, radius: 0 },
    ]);
    for (const cp of flat.cp) expect(Number.isFinite(cp)).toBe(true);
  });
});
